### PR TITLE
Upgrade to rails 4.2, remove some files and start cleaning things up

### PR DESCRIPTION
**Pull request by oponder**
WIP

### CODE REVIEW

**Comment by 501st-alpha1** [comment]
I got this branch running locally; looks great!

**Comment by oponder** [comment]
Awesome! Thanks for giving it a spin :)

I'll be cleaning up the CSS and rounding off the rest of the changes I wanted to make this weekend.

**Comment by 501st-alpha1** [comment]
Any updates here?

**Comment by oponder** [comment]
Hi Scott. Yup! Planning on working on this again this Friday and weekend. The remaining tasks should be done then.

**Pull request merged**
